FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["SistemaVotoElectronico.API/SistemaVotoElectronico.API.csproj", "SistemaVotoElectronico.API/"]
COPY ["SistemaVoto.Modelos/SistemaVoto.Modelos.csproj", "SistemaVoto.Modelos/"]
RUN dotnet restore "SistemaVotoElectronico.API/SistemaVotoElectronico.API.csproj"
COPY . .
WORKDIR "/src/SistemaVotoElectronico.API"
RUN dotnet build "SistemaVotoElectronico.API.csproj" -c Release -o /app/build
FROM build AS publish
RUN dotnet publish "SistemaVotoElectronico.API.csproj" -c Release -o /app/publish /p:UseAppHost=false
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080
ENTRYPOINT ["dotnet", "SistemaVotoElectronico.API.dll"]