// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaVotoElectronico.API.Data;

#nullable disable

namespace SistemaVotoElectronico.API.Migrations
{
    [DbContext(typeof(VotoContext))]
    [Migration("20260127204258_AgregadoJefeDeJuntas")]
    partial class AgregadoJefeDeJuntas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaVoto.Modelos.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Dignidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartidoPolitico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProcesoElectoralId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcesoElectoralId");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Canton", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Cantones");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Junta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<int>("ZonaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ZonaId");

                    b.ToTable("Juntas");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Parroquia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantonId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CantonId");

                    b.ToTable("Parroquias");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.ProcesoElectoral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProcesoElectorales");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.TokenVotacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoUnico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("FueUsado")
                        .HasColumnType("boolean");

                    b.Property<int>("VotanteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodigoUnico")
                        .IsUnique();

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Votante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsJefe")
                        .HasColumnType("boolean");

                    b.Property<int>("JuntaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("YaVoto")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("JuntaId");

                    b.ToTable("Votantes");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CandidatoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaVoto")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdVotante")
                        .HasColumnType("integer");

                    b.Property<int>("ProcesoElectoralId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("IdVotante");

                    b.HasIndex("ProcesoElectoralId");

                    b.ToTable("Votos");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Zona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParroquiaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParroquiaId");

                    b.ToTable("Zonas");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Candidato", b =>
                {
                    b.HasOne("SistemaVoto.Modelos.ProcesoElectoral", "ProcesoElectoral")
                        .WithMany("Candidatos")
                        .HasForeignKey("ProcesoElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcesoElectoral");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Canton", b =>
                {
                    b.HasOne("SistemaVoto.Modelos.Provincia", "Provincia")
                        .WithMany("Cantones")
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Junta", b =>
                {
                    b.HasOne("SistemaVoto.Modelos.Zona", "Zona")
                        .WithMany("Juntas")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Parroquia", b =>
                {
                    b.HasOne("SistemaVoto.Modelos.Canton", "Canton")
                        .WithMany("Parroquias")
                        .HasForeignKey("CantonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canton");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Votante", b =>
                {
                    b.HasOne("SistemaVoto.Modelos.Junta", "Junta")
                        .WithMany()
                        .HasForeignKey("JuntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Junta");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Voto", b =>
                {
                    b.HasOne("SistemaVoto.Modelos.Candidato", "Candidato")
                        .WithMany()
                        .HasForeignKey("CandidatoId");

                    b.HasOne("SistemaVoto.Modelos.Votante", "Votante")
                        .WithMany()
                        .HasForeignKey("IdVotante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVoto.Modelos.ProcesoElectoral", "ProcesoElectoral")
                        .WithMany("Votos")
                        .HasForeignKey("ProcesoElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidato");

                    b.Navigation("ProcesoElectoral");

                    b.Navigation("Votante");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Zona", b =>
                {
                    b.HasOne("SistemaVoto.Modelos.Parroquia", "Parroquia")
                        .WithMany("Zonas")
                        .HasForeignKey("ParroquiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parroquia");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Canton", b =>
                {
                    b.Navigation("Parroquias");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Parroquia", b =>
                {
                    b.Navigation("Zonas");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.ProcesoElectoral", b =>
                {
                    b.Navigation("Candidatos");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Provincia", b =>
                {
                    b.Navigation("Cantones");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Zona", b =>
                {
                    b.Navigation("Juntas");
                });
#pragma warning restore 612, 618
        }
    }
}
