// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaVotoElectronico.API.Data;

#nullable disable

namespace SistemaVotoElectronico.API.Migrations
{
    [DbContext(typeof(VotoElectronicoContext))]
    [Migration("20260115154501_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaVotoElectronico.API.Models.Parroquia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Parroquias");
                });

            modelBuilder.Entity("SistemaVotoElectronico.API.Models.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("SistemaVotoElectronico.API.Models.Seccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParroquiaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParroquiaId");

                    b.ToTable("Secciones");
                });

            modelBuilder.Entity("SistemaVotoElectronico.API.Models.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashSeguridad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeccionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Votos");
                });

            modelBuilder.Entity("SistemaVotoElectronico.API.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoAcceso")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeccionId")
                        .HasColumnType("integer");

                    b.Property<bool>("YaVoto")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaVotoElectronico.API.Models.Parroquia", b =>
                {
                    b.HasOne("SistemaVotoElectronico.API.Models.Provincia", null)
                        .WithMany("Parroquias")
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaVotoElectronico.API.Models.Seccion", b =>
                {
                    b.HasOne("SistemaVotoElectronico.API.Models.Parroquia", null)
                        .WithMany("Secciones")
                        .HasForeignKey("ParroquiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaVotoElectronico.API.Models.Parroquia", b =>
                {
                    b.Navigation("Secciones");
                });

            modelBuilder.Entity("SistemaVotoElectronico.API.Models.Provincia", b =>
                {
                    b.Navigation("Parroquias");
                });
#pragma warning restore 612, 618
        }
    }
}
